# sonar-project.properties
sonar.projectKey=tomadonna1_8.2CDevSecOps
sonar.organization=tomadonna1
sonar.host.url=https://sonarcloud.io
sonar.login=${5962815eb5fb9cd09a7890ecbcc11e7a07c88f36}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8